name: Test Compilation

# on: [push, pull_request]
on: [push]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # - name: Install required build toolchain
      # if: matrix.os == 'ubuntu-latest'
      # run: sudo apt-get install gcc-multilib g++-multilib

      - name: Enable Corepack
        run: corepack enable
        env:
          ADBLOCK: true

      - name: Install Yarn Berry
        run: corepack prepare yarn@stable --activate
        env:
          ADBLOCK: true

      - name: Set Yarn version
        run: yarn set version stable
        env:
          ADBLOCK: true

      - name: Install dependencies
        run: yarn install --mode update-lockfile
        env:
          ADBLOCK: true

      - name: Get commit message
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
  
      - name: Does installing work?
        run: yarn

      - name: Does building work?
        run: yarn build

      - name: Done
        run: echo Done
